AY2223S1-CS2103T-W10-1/tp

- docs/UserGuide.md
> Add user guide introduction and list of contents

- docs/UserGuide.md
Links to jump to the relevant parts of the user guide have been added.
> Edit formatting for User Guide Introduction

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/_config.yml
- docs/_sass/minima/_base.scss
- Updated command summary
- Edited _config.yml file title and repository to "TABS" and "AY2223S1-CS2103T-W10-1/tp
> Edit _config.yml file

- docs/UserGuide.md
trying to solve the rendering issue on github pages
> Fix command summary table borders

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/EditUserByNameCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/EditByNameCommandParser.java
- src/main/java/seedu/address/model/person/FullNamePredicate.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/EditByNameCommandParserTest.java
Update EditByNameCommand.
Add predicate (hard regex) to check between user input and full name in addressbook.
Add EditByNameCommandParserTest to increase code coverage.
Closes #60
> Branch update editbynamecommand

- src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/AddressBook.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
- src/test/java/seedu/address/logic/parser/AddGroupCommandParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteGroupCommandParserTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/group/testutil/TypicalGroups.java
- src/test/java/seedu/address/model/person/testutil/TypicalPersons.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Adds JUnit Test Cases for the following classes:
- LogicManager
- AddressBook
- ModelManager
- AddGroupParserCommand
- AddGroupCommand
- DeleteGroupParserCommand
- DeleteGroupCommand
> Branch testing (DO NOT MERGE BEFORE STORAGE)

- src/main/java/seedu/address/logic/parser/AddGroupMemberCommandParser.java
- src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/commands/AddGroupMemberCommandTest.java
- src/test/java/seedu/address/logic/parser/AddGroupMemberCommandParserTest.java
- src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- AddGroupMemberCommand
- AddGroupMemberCommandParser
- FullNamePredicateTest
- withGroups method in ParserUtil
> Add testcases [ merge ]

- src/main/java/seedu/address/logic/commands/DisplayGroupCommand.java
- src/test/java/seedu/address/logic/commands/DisplayGroupCommandTest.java
- src/test/java/seedu/address/logic/parser/DisplayGroupCommandParserTest.java
**Add testcases for the following classes**
-  DisplayGroupCommand.java
- DisplayGroupCommandParser.java
> Branch testsfordisplaygroup

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
- src/main/java/seedu/address/logic/commands/EditPersonCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
- src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
- src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
- src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
- src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
Add test cases for the following:
Editpersoncommand
Editpersoncommandparser
Deletepersoncommand
> Add test cases

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/AssignTaskCommand.java
- src/main/java/seedu/address/logic/parser/AssignTaskCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/DateTimeParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/assignment/Assignment.java
- src/main/java/seedu/address/model/assignment/Deadline.java
- src/main/java/seedu/address/model/assignment/Workload.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/ui/PersonCard.java
In this merge, workload and deadline is added to assignments.
- Workload can be categorised as LOW, MEDIUM or HIGH. User can only input these three words (ignore casing) when parsing.
- Workload is an enum class.
- Throws parseException if user does not input one of these three values.
- Deadline contains a LocalDateTime field. Deadline must be in the form of yyyy-MM-dd or yyyy-MM-dd HH:mm when parsing.
- Added DateTimeParser to parse Strings to LocalDateTime.
- Throws parseException when user does not input the correct format of deadline.
- An assignment must have workload but deadline is optional.
- Made assignments implement comparator to sort the list based on workload.
Sample of implementation:
- Currently the assignment toString() is made to print the new fields as such in the …
> Branch add workload and deadline [DO NOT MERGE YET]

- src/main/java/seedu/address/logic/commands/AssignTaskAllCommand.java
- src/main/java/seedu/address/logic/commands/AssignTaskCommand.java
- src/main/java/seedu/address/logic/commands/DeleteTaskAllCommand.java
- src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
- src/main/java/seedu/address/model/assignment/Workload.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
Adds a workload score to person. UI to be displayed as coloured border for person.
Workload high = 5, medium = 3, low = 1. (might change score range)
Add placeholder workload in fxml to display in GUI (to be changed to display coloured).
Each time assign, assignall, delete, deleteall task is executed, setWorkloadScore() is called to change workload.
> Add a workload score to person (Logic for UI) [DO NOT MERGE YET]

- src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
- src/main/java/seedu/address/ui/AssignmentCard.java
Throw exception if user tries to delete a person who is still in any existing groups.
Added colours to represent workload in the assignment tab, so that the overall workload can be seen on both both tabs.
> Fix deleteperson bug and add workload colours to assignments tab

- src/main/java/seedu/address/model/assignment/Assignment.java
- src/main/java/seedu/address/ui/AssignmentCard.java
- src/test/java/seedu/address/logic/commands/AssignTaskCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/AssignTaskCommandParserTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/model/person/testutil/PersonBuilder.java
Fix current failing test cases by accounting for workload in assignment creation.
By default in tests, building a person withAssignments() will create a task with LOW workload.
> Fix current failing test cases

- src/main/java/seedu/address/model/assignment/Assignment.java
- src/main/java/seedu/address/model/assignment/Workload.java
- src/main/java/seedu/address/ui/AssignmentCard.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/test/java/seedu/address/model/person/PersonTest.java
Improve RGB to make colour transition more gradual.
Make assignmentlist neater:
> Improve RGB

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/DeleteGroupMemberCommand.java
- src/main/java/seedu/address/logic/commands/EditPersonCommand.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
User guide 
- Removed `TASK is of type String` from user guide.
- Added missing whitespaces 
EditPersonCommand and DeleteMemberCommand
- Fix the bug where both commands are not updating the GroupList when the details of the member are changed.
> Fix bugs for User Guide, EditPersonCommand and DeleteMemberCommand

- README.md
- build.gradle
- docs/index.md
- Update UG and DG links for index.md and README
- Enable assertions for build.gradle
> Update index.md and README 

- src/main/java/seedu/address/ui/AssignmentCard.java
- src/main/java/seedu/address/ui/GroupCard.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/AssignmentListCard.fxml
- src/main/resources/view/GroupListCard.fxml
- src/main/resources/view/HelpWindow.fxml
- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/StatusBarFooter.fxml
> Fix Text overflow for flowpane for person tags, person groups, assignments and group members

- build.gradle
- src/main/resources/view/HelpWindow.fxml
- src/main/resources/view/MainWindow.fxml
- Edited HelpWindow.fxml to ensure help window stage adheres to minimum size requirements.
- Also updated FXML to version 11.0.2, to ensure compatibility with Linux machines.
> JavaFX Edits

- docs/UserGuide.md
- docs/team/cedricchia123.md
- docs/team/lianguoyang.md
- docs/team/tan-jin-waye.md
- docs/team/zylee348.md
> Update PPP, fix checkstyle

- docs/UserGuide.md
> Remove notebox to fix formatting

- docs/UserGuide.md
> Fix assigntaskall extra note

- docs/UserGuide.md
Fix formatting for PDF conversion
> Fix formatting for PDF conversion

- docs/UserGuide.md
> Remove extra page in UG PDF

- docs/AboutUs.md
- docs/UserGuide.md
Update About Us and minor UG change
> Update About Us and minor UG change

- docs/team/lianguoyang.md
- Finalize PPP for lianguoyang
> Finalize PPP for lianguoyang

- docs/team/cedricchia123.md
> Change link
